spring:
  application:
    name: simple-microservice
server:
  port: 9998
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.kafka: info
    org.springframework.web: debug
---
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 10
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: pwd